export enum Routers {
  REGISTRATION = "/registration",
  LOGIN = "/login",
  LOGOUT = "/logout",
  ACTIVE = "/active/:link",
  REFRESH = "/refresh",
  USERS = "/users",
  SEARCH_USERS = "/search-users",
  UPDATE_USER = "/update-user",
  GET_USER = "/user",
  GET_USER_BY_ID = "/users/:id",
  CHAT_START = "/chat/start",
  CHAT_GET = "/chat/:id",
  CHAT_MESSAGES_GET = "/chat/:id/messages",
  CHAT_MESSAGES = "/chat/messages",
  CHAT_ADD_CONTACT = "/chat/add-contact",
  CHAT_CONTACTS = "/chat/contacts",
  CHAT_REMOVE = "/chat/remove-contact/:id",
  USER_STATUS = "/users/status",
}
