cat > docker-compose.yml << 'EOF'
version: "3.8"

services:
  client:
    image: meet-app-client:latest
    build:
      context: ./client
      dockerfile: ./Dockerfile
      args:
        - VITE_WS_URL="${VITE_WS_URL}"
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
      - "${WS_PORT}:${WS_PORT}"
    environment:
      - PORT=${CLIENT_PORT}
      - WS_PORT=${WS_PORT}
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
EOF