services:
  server:
    image: meet-app-server:latest
    build:
      context: ./backend/auth-service
      dockerfile: Dockerfile
      args:
        - PORT=${PORT}
        - ROUTER_API=${ROUTER_API}
        - JWT_ACCESS_SECRET_KEY=${JWT_ACCESS_SECRET_KEY}
        - JWT_REFRESH_SECRET_KEY=${JWT_REFRESH_SECRET_KEY}
        - DB_URL=${DB_URL}
        - CLIENT_URL=${CLIENT_URL}
        - SMTP_HOST=${SMTP_HOST}
        - SMTP_PORT=${SMTP_PORT}
        - SMTP_USER=${SMTP_USER}
        - SMTP_PASSWORD=${SMTP_PASSWORD}
        - API_URL=${API_URL}
        - SERVER_PORT=${SERVER_PORT}
    ports:
      - "${SERVER_PORT}:5000"
    environment:
      - PORT=${PORT}
      - ROUTER_API=${ROUTER_API}
      - JWT_ACCESS_SECRET_KEY=${JWT_ACCESS_SECRET_KEY}
      - JWT_REFRESH_SECRET_KEY=${JWT_REFRESH_SECRET_KEY}
      - DB_URL=${DB_URL}
      - CLIENT_URL=${CLIENT_URL}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - API_URL=${API_URL}
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge