services:
  server:
    image: meet-app-server:latest
    build:
      context: ./backend/auth-service
      dockerfile: Dockerfile
      args:
        - PORT=${PORT}
    ports:
      - "${SERVER_PORT}:5000"
    environment:
      - PORT=${PORT}
      - DB_URL=${DB_URL}
      - JWT_ACCESS_SECRET=${JWT_ACCESS_SECRET}
      - JWT_REFRESH_SECRET=${JWT_REFRESH_SECRET}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - SMTP_USER=${SMTP_USER}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - API_URL=${API_URL}
      - CLIENT_URL=${CLIENT_URL}
    restart: always
    networks:
      - app-network
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  mongodb_data: