version: "3.8"

services:
  client:
    image: meet-app-client:latest
    build:
      context: ./client
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=${VITE_API_URL}
        - VITE_WS_URL=${VITE_WS_URL}
        - CLIENT_PORT=${CLIENT_PORT}
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    environment:
      - VITE_API_URL=${VITE_API_URL}
      - VITE_WS_URL=${VITE_WS_URL}
      - CLIENT_PORT=${CLIENT_PORT}
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge