name: meet-app-deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches: ["main"]

jobs:
  build-app:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: [self-hosted, meet-app]
    env:
      VITE_API_URL: ${{ secrets.VITE_API_URL }}
      VITE_WS_URL: ${{ secrets.VITE_WS_URL }}
      CLIENT_PORT: ${{ secrets.CLIENT_PORT }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: './client/.nvmrc'
      - name: Install dependencies
        working-directory: ./client
        run: npm ci
      - name: Debug environment
        run: |
          echo "VITE_API_URL=$VITE_API_URL"
          echo "VITE_WS_URL=$VITE_WS_URL"
          echo "CLIENT_PORT=$CLIENT_PORT"
      - name: Build the client Docker image
        working-directory: ./client
        run: docker build . -t meet-app-client -f Dockerfile --build-arg VITE_API_URL=$VITE_API_URL --build-arg VITE_WS_URL=$VITE_WS_URL --build-arg CLIENT_PORT=$CLIENT_PORT
      - name: Check images
        run: docker images | grep -E "meet-app-client"

  remove-container-app:
    runs-on: [self-hosted, meet-app]
    needs: build-app
    steps:
      - uses: actions/checkout@v4
      - name: Remove old Docker containers
        run: docker-compose down || true

  start-app:
    runs-on: [self-hosted, meet-app]
    needs: remove-container-app
    env:
      VITE_API_URL: ${{ secrets.VITE_API_URL }}
      VITE_WS_URL: ${{ secrets.VITE_WS_URL }}
      CLIENT_PORT: ${{ secrets.CLIENT_PORT }}
    steps:
      - uses: actions/checkout@v4
      - name: Debug environment
        run: |
          echo "VITE_API_URL=$VITE_API_URL"
          echo "VITE_WS_URL=$VITE_WS_URL"
          echo "CLIENT_PORT=$CLIENT_PORT"
      - name: Debug Docker Compose config
        run: docker-compose config
      - name: Start application
        run: docker-compose up -d