name: meet-app-deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches: ["main"]

jobs:
  build-app:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: [self-hosted, meet-app]
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: './client/.nvmrc'
      - name: Install dependencies
        working-directory: ./client
        run: npm ci
      - name: Create environment file
        working-directory: ./client
        run: |
          echo "VITE_WS_URL=${{ secrets.VITE_WS_URL }}" > .env
          echo "VITE_API_URL=${{ secrets.VITE_API_URL }}" >> .env
          echo "CLIENT_PORT=${{ secrets.CLIENT_PORT }}" >> .env
      - name: Debug environment
        working-directory: ./client
        run: |
          cat .env
          ls -la
      - name: Build the client Docker image
        working-directory: ./client
        run: docker build . -t meet-app-client -f Dockerfile
      - name: Build Docker Compose
        run: docker compose build --no-cache
      - name: Check images
        run: docker images | grep -E "meet-app-client"

  remove-container-app:
    runs-on: [self-hosted, meet-app]
    needs: build-app
    steps:
      - uses: actions/checkout@v4
      - name: Remove old Docker containers
        run: docker compose down || true

  start-app:
    runs-on: [self-hosted, meet-app]
    needs: remove-container-app
    steps:
      - uses: actions/checkout@v4
      - name: Debug Docker Compose config
        run: |
          cat ./client/.env
          docker compose --env-file ./client/.env config
      - name: Start application
        run: docker compose --env-file ./client/.env up -d