name: meet-app-server-deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:
    branches: ["main"]

jobs:
  build-server:
    if: ${{ github.ref == 'refs/heads/main' }}
    runs-on: [self-hosted, meet-app]
    needs: start-app
    env:
      PORT: ${{ secrets.SERVER_PORT }}
      DB_URL: ${{ secrets.DB_URL }}
      JWT_ACCESS_SECRET: ${{ secrets.JWT_ACCESS_SECRET }}
      JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}
      SMTP_HOST: ${{ secrets.SMTP_HOST }}
      SMTP_PORT: ${{ secrets.SMTP_PORT }}
      SMTP_USER: ${{ secrets.SMTP_USER }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      API_URL: ${{ secrets.API_URL }}
      CLIENT_URL: ${{ secrets.CLIENT_URL }}
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.12.1'
      - name: Create .env file for deployment
        run: |
          echo "PORT=$PORT" > ./server/auth-service/.env
          echo "DB_URL=$DB_URL" >> ./server/auth-service/.env
          echo "JWT_ACCESS_SECRET=$JWT_ACCESS_SECRET" >> ./server/auth-service/.env
          echo "JWT_REFRESH_SECRET=$JWT_REFRESH_SECRET" >> ./server/auth-service/.env
          echo "SMTP_HOST=$SMTP_HOST" >> ./server/auth-service/.env
          echo "SMTP_PORT=$SMTP_PORT" >> ./server/auth-service/.env
          echo "SMTP_USER=$SMTP_USER" >> ./server/auth-service/.env
          echo "SMTP_PASSWORD=$SMTP_PASSWORD" >> ./server/auth-service/.env
          echo "API_URL=$API_URL" >> ./server/auth-service/.env
          echo "CLIENT_URL=$CLIENT_URL" >> ./server/auth-service/.env
          echo "Created .env file:"
          cat ./server/auth-service/.env
      - name: Install dependencies
        working-directory: ./server/auth-service
        run: npm ci
      - name: Build the server
        working-directory: ./server/auth-service
        run: npm run build
      - name: Build the server Docker image
        working-directory: ./server/auth-service
        run: docker build . -t meet-app-server -f Dockerfile --build-arg PORT=$PORT
      - name: Check images
        run: docker images | grep -E "meet-app-server"

  remove-container-server:
    runs-on: [self-hosted, meet-app]
    needs: build-server
    steps:
      - uses: actions/checkout@v4
      - name: Remove old Docker containers
        run: docker-compose -f docker-compose-server.yml down || true

  start-server:
    runs-on: [self-hosted, meet-app]
    needs: remove-container-server
    env:
      PORT: ${{ secrets.SERVER_PORT }}
      DB_URL: ${{ secrets.DB_URL }}
      JWT_ACCESS_SECRET: ${{ secrets.JWT_ACCESS_SECRET }}
      JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}
      SMTP_HOST: ${{ secrets.SMTP_HOST }}
      SMTP_PORT: ${{ secrets.SMTP_PORT }}
      SMTP_USER: ${{ secrets.SMTP_USER }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      API_URL: ${{ secrets.API_URL }}
      CLIENT_URL: ${{ secrets.CLIENT_URL }}
    steps:
      - uses: actions/checkout@v4
      - name: Create .env file for deployment
        run: |
          echo "PORT=$PORT" > ./server/auth-service/.env
          echo "DB_URL=$DB_URL" >> ./server/auth-service/.env
          echo "JWT_ACCESS_SECRET=$JWT_ACCESS_SECRET" >> ./server/auth-service/.env
          echo "JWT_REFRESH_SECRET=$JWT_REFRESH_SECRET" >> ./server/auth-service/.env
          echo "SMTP_HOST=$SMTP_HOST" >> ./server/auth-service/.env
          echo "SMTP_PORT=$SMTP_PORT" >> ./server/auth-service/.env
          echo "SMTP_USER=$SMTP_USER" >> ./server/auth-service/.env
          echo "SMTP_PASSWORD=$SMTP_PASSWORD" >> ./server/auth-service/.env
          echo "API_URL=$API_URL" >> ./server/auth-service/.env
          echo "CLIENT_URL=$CLIENT_URL" >> ./server/auth-service/.env
      - name: Debug Docker Compose config
        run: docker-compose -f docker-compose-server.yml config
      - name: Start server
        run: docker-compose -f docker-compose-server.yml up -d