name: meet-app-server-deploy

on:
  workflow_run:
    workflows: ["meet-app-deploy"]
    types:
      - completed

jobs:
  build-server:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: [self-hosted, meet-app]
    env:
      PORT: ${{ secrets.SERVER_PORT }}
      DB_URL: ${{ secrets.DB_URL }}
      JWT_ACCESS_SECRET: ${{ secrets.JWT_ACCESS_SECRET }}
      JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}
      SMTP_HOST: ${{ secrets.SMTP_HOST }}
      SMTP_PORT: ${{ secrets.SMTP_PORT }}
      SMTP_USER: ${{ secrets.SMTP_USER }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      API_URL: ${{ secrets.API_URL }}
      CLIENT_URL: ${{ secrets.CLIENT_URL }}
    steps:
      - uses: actions/checkout@v4
      - name: Debug directory structure
        run: ls -la ./backend/auth-service || echo "Directory backend/auth-service not found"
      - name: Debug environment variables
        run: echo "PORT is set to $PORT"
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.12.1'
      - name: Create .env file for deployment
        run: |
          mkdir -p ./backend/auth-service
          echo "PORT=$PORT" > ./backend/auth-service/.env
          echo "DB_URL=$DB_URL" >> ./backend/auth-service/.env
          echo "JWT_ACCESS_SECRET=$JWT_ACCESS_SECRET" >> ./backend/auth-service/.env
          echo "JWT_REFRESH_SECRET=$JWT_REFRESH_SECRET" >> ./backend/auth-service/.env
          echo "SMTP_HOST=$SMTP_HOST" >> ./backend/auth-service/.env
          echo "SMTP_PORT=$SMTP_PORT" >> ./backend/auth-service/.env
          echo "SMTP_USER=$SMTP_USER" >> ./backend/auth-service/.env
          echo "SMTP_PASSWORD=$SMTP_PASSWORD" >> ./backend/auth-service/.env
          echo "API_URL=$API_URL" >> ./backend/auth-service/.env
          echo "CLIENT_URL=$CLIENT_URL" >> ./backend/auth-service/.env
          echo "Created .env file:"
          cat ./backend/auth-service/.env
      - name: Install dependencies
        working-directory: ./backend/auth-service
        run: npm ci
      - name: Build the server
        working-directory: ./backend/auth-service
        run: npm run build
      - name: Build the server Docker image
        working-directory: ./backend/auth-service
        run: docker build . -t meet-app-server -f Dockerfile --build-arg PORT=$PORT
      - name: Check images
        run: docker images | grep -E "meet-app-server"

  remove-container-server:
    runs-on: [self-hosted, meet-app]
    needs: build-server
    steps:
      - uses: actions/checkout@v4
      - name: Remove old Docker containers
        run: docker-compose -f docker-compose-server.yml down || true
      - name: Clean up unused Docker images
        run: docker image prune -f

  start-server:
    runs-on: [self-hosted, meet-app]
    needs: remove-container-server
    env:
      PORT: ${{ secrets.SERVER_PORT }}
      DB_URL: ${{ secrets.DB_URL }}
      JWT_ACCESS_SECRET: ${{ secrets.JWT_ACCESS_SECRET }}
      JWT_REFRESH_SECRET: ${{ secrets.JWT_REFRESH_SECRET }}
      SMTP_HOST: ${{ secrets.SMTP_HOST }}
      SMTP_PORT: ${{ secrets.SMTP_PORT }}
      SMTP_USER: ${{ secrets.SMTP_USER }}
      SMTP_PASSWORD: ${{ secrets.SMTP_PASSWORD }}
      API_URL: ${{ secrets.API_URL }}
      CLIENT_URL: ${{ secrets.CLIENT_URL }}
    steps:
      - uses: actions/checkout@v4
      - name: Check Client Health
        run: curl --fail http://${CLIENT_URL} || echo "Client health check failed"
      - name: Create .env file for deployment
        run: |
          mkdir -p ./backend/auth-service
          echo "PORT=$PORT" > ./backend/auth-service/.env
          echo "DB_URL=$DB_URL" >> ./backend/auth-service/.env
          echo "JWT_ACCESS_SECRET=$JWT_ACCESS_SECRET" >> ./backend/auth-service/.env
          echo "JWT_REFRESH_SECRET=$JWT_REFRESH_SECRET" >> ./backend/auth-service/.env
          echo "SMTP_HOST=$SMTP_HOST" >> ./backend/auth-service/.env
          echo "SMTP_PORT=$SMTP_PORT" >> ./backend/auth-service/.env
          echo "SMTP_USER=$SMTP_USER" >> ./backend/auth-service/.env
          echo "SMTP_PASSWORD=$SMTP_PASSWORD" >> ./backend/auth-service/.env
          echo "API_URL=$API_URL" >> ./backend/auth-service/.env
          echo "CLIENT_URL=$CLIENT_URL" >> ./backend/auth-service/.env
          echo "Created .env file:"
          cat ./backend/auth-service/.env
      - name: Debug Docker Compose config
        run: docker-compose -f docker-compose-server.yml config
      - name: Start server
        run: docker-compose -f docker-compose-server.yml up -d